/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {
    @Test fun applicationTest() {
        // Basic test to verify the test infrastructure is working
        assertTrue(true, "test infrastructure should work")
    }
}
